### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by trebmuh** [klangfreund/SpectrumAnalyser#1]
What licence is this released on?
I couldn't find this information.

**Comment by klangfreund** [comment]
It inherits the license of the JUCE library it uses:

Permission is granted to use this software under the terms of either:
   a) the GPL v2 (or any later version)
   b) the Affero GPL v3

**Comment by trebmuh** [comment]
Thanks for your quick answer. Much appreciated.
What about putting a license file in the root folder making it clearer?

**Comment by klangfreund** [comment]
I've added a Readme including license information. Thanks for the heads-up.

**Comment by trebmuh** [comment]
Glad it helped, you're welcome.
