### ISSUE TITLE
Could the branding be moved to a "About" section?

### ISSUE THREAD

**Issue by unfa** [klangfreund/SpectrumAnalyser#2]
I really like the look of this spectrogram, but the huge "Studio 571" caption and the face and contact info visible at all times are a bit obscure and make if feel wird.

if these things could be moved to an "About" section accesible via a small button somewhere - that'd improve the look of the plugin IMHO.

Also - the 571 studio website is down: www.571.ch/en/about-571/

**Comment by klangfreund** [comment]
I'm glad you like it! This was just a weekend project without any ambitions. Its main purpose was to function as a job application. At the moment I don't have time to work on it. To get rid of the logo, outcomment the 571 section in SpectrumViewer::paint(Graphics& g).
